const cases=ALL_CASES;
const I18N={uk:{inventory:'ІНВЕНТАР',heroTitle:'Відкрий<br><em>свій</em> дроп.',heroLead:'Інтерактивний симулятор кейсів CS2. Усі предмети — віртуальні, без депозитів і реальної вартості.',chooseCase:'ОБРАТИ КЕЙС <span>↓</span>',caseStep:'01 / ВИБІР КЕЙСУ',openCase:'ВІДКРИЙ КЕЙС',caseHint:'Натисни на кейс — далі рулетка визначить твій дроп.',buyOpen:'КУПИТИ ТА ВІДКРИТИ',clickStep:'BONUS / КЛІКЕР',clickTitle:'ЗАРОБИ МОНЕТИ',clickLead:'Натискай на жетон, щоб купувати кейси. Це лише ігрова валюта.',coinsLabel:'МОНЕТ',inventoryStep:'04 / ТВОЯ КОЛЕКЦІЯ',empty:'Ще порожньо. Відкрий перший кейс.',pool:'ПРЕДМЕТІВ У ПУЛІ',selected:'У пулі',need:'Недостатньо монет',sell:'ПРОДАТИ',won:'Ти вибив',spinning:'Крутиться...'},ru:{inventory:'ИНВЕНТАРЬ',heroTitle:'Открой<br><em>свой</em> дроп.',heroLead:'Интерактивный симулятор кейсов CS2. Все предметы виртуальные, без депозитов и реальной стоимости.',chooseCase:'ВЫБРАТЬ КЕЙС <span>↓</span>',caseStep:'01 / ВЫБОР КЕЙСА',openCase:'ОТКРОЙ КЕЙС',caseHint:'Нажми на кейс — дальше рулетка определит твой дроп.',buyOpen:'КУПИТЬ И ОТКРЫТЬ',clickStep:'BONUS / КЛИКЕР',clickTitle:'ЗАРАБОТАЙ МОНЕТЫ',clickLead:'Нажимай на жетон, чтобы покупать кейсы. Это только игровая валюта.',coinsLabel:'МОНЕТ',inventoryStep:'04 / ТВОЯ КОЛЛЕКЦИЯ',empty:'Пока пусто. Открой первый кейс.',pool:'ПРЕДМЕТОВ В ПУЛЕ',selected:'В пуле',need:'Недостаточно монет',sell:'ПРОДАТЬ',won:'Ты выбил',spinning:'Крутится...'},en:{inventory:'INVENTORY',heroTitle:'Open<br><em>your</em> drop.',heroLead:'An interactive CS2 case simulator. Every item is virtual, with no deposits or real-world value.',chooseCase:'CHOOSE CASE <span>↓</span>',caseStep:'01 / CASE SELECTION',openCase:'OPEN A CASE',caseHint:'Choose a case — then the roulette decides your drop.',buyOpen:'BUY & OPEN',clickStep:'BONUS / CLICKER',clickTitle:'EARN COINS',clickLead:'Tap the token to earn coins for cases. This is game currency only.',coinsLabel:'COINS',inventoryStep:'04 / YOUR COLLECTION',empty:'Nothing here yet. Open your first case.',pool:'ITEMS IN POOL',selected:'Pool',need:'Not enough coins',sell:'SELL',won:'You unboxed',spinning:'Spinning...'}};
let lang=localStorage.getItem('caselab-lang')||'uk',selected=null,spinning=false,upgrading=false;
let state=JSON.parse(localStorage.getItem('caselab-save')||'{"coins":25,"inventory":[]}');
state.redeemed??=[];
const allSkins=Object.values(CASE_POOLS).flat(),$=s=>document.querySelector(s),t=()=>I18N[lang];
function save(){localStorage.setItem('caselab-save',JSON.stringify(state))}
function tone(freq,duration=.07,type='sine',volume=.04){try{const audio=new (window.AudioContext||window.webkitAudioContext)(),osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audio.currentTime);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}catch{}}
function sound(kind){if(kind==='click'){tone(690,.05,'square');setTimeout(()=>tone(980,.07,'sine'),40)}if(kind==='open'){tone(130,.13,'sawtooth');setTimeout(()=>tone(220,.12,'square'),120)}if(kind==='win'){tone(520,.1);setTimeout(()=>tone(780,.13),100);setTimeout(()=>tone(1040,.2),210)}if(kind==='sell'){tone(880,.05);setTimeout(()=>tone(1180,.08),60)}}
function value(s){const base=s.rare?900:({'Covert':300,'Classified':100,'Restricted':40,'Mil-Spec Grade':15}[s.r]||25);let h=0;for(const c of s.n)h=(h*31+c.charCodeAt(0))>>>0;return Math.round(base+(h%Math.max(8,base)))}
function itemName(s){return s.n}
function card(s,mode='',index=-1){const action=mode==='owned'?`<button type="button" class="sell-button" data-sell="${index}" aria-label="Продати скін" title="Продати скін">+$${value(s)}</button>`:mode==='buy'?`<button type="button" class="buy-skin" data-buy="${index}">КУПИТИ $${value(s)}</button>`:'';return `<div class="skin-card" style="--rarity:${s.c}"><img class="skin-image" src="${s.image}" alt="${s.n}" loading="lazy" onerror="this.style.display='none'"><span class="type">${s.r}</span><strong>${itemName(s)}</strong>${action}<div class="rarity"></div></div>`}
function renderCases(){const grid=$('#caseGrid');grid.innerHTML=cases.map((x,i)=>`<article class="case" data-id="${i}" style="--case:${x.color}"><small>${ALL_CASE_POOLS[x.source].length} ${t().pool}</small><div class="case-box has-image"><img src="${x.image}" alt="${x.name}"></div><div class="case-name">${x.name}</div><div class="case-price">$${x.price}</div></article>`).join('')}
function updateWallet(){ $('#coins').textContent=`$${state.coins}`;$('#clickCoins').textContent=`$${state.coins}`;$('#count').textContent=state.inventory.length }
function renderInventory(){const el=$('#inventoryGrid');el.innerHTML=state.inventory.length?state.inventory.map((s,i)=>card(s,'owned',i)).join(''):`<div class="empty">${t().empty}</div>`;updateWallet();renderUpgrade()}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t()[el.dataset.i18n]);$('#inventoryBtn').innerHTML=`${t().inventory} <b id="count">${state.inventory.length}</b>`;$('#language').value=lang;$('#promoTitle').textContent=lang==='uk'?'ПРОМОКОД':lang==='ru'?'ПРОМОКОД':'PROMO CODE';$('#promoHint').textContent=lang==='uk'?'Введи код, щоб отримати ігрові монети.':lang==='ru'?'Введи код, чтобы получить игровые монеты.':'Enter a code to receive game coins.';renderCases();renderCatalog($('#filters .active')?.dataset.filter||'all');renderInventory();if(selected){$('#openTitle').textContent=selected.name;$('#openBtn').querySelector('span').textContent=t().buyOpen}}
function pool(){return ALL_CASE_POOLS[selected.source]}
function weighted(){const items=pool(),rare=items.filter(x=>x.rare),regular=items.filter(x=>!x.rare);if(Math.random()<.026)return rare[Math.floor(Math.random()*rare.length)];const roll=Math.random(),weights={'Covert':.0064,'Classified':.032,'Restricted':.1598,'Mil-Spec Grade':.8018};let total=0;for(const [rarity,chance] of Object.entries(weights)){total+=chance;if(roll<total){const group=regular.filter(x=>x.r===rarity);if(group.length)return group[Math.floor(Math.random()*group.length)]}}return regular[Math.floor(Math.random()*regular.length)]}
function preview(){const r=$('#roulette');r.style.transition='none';r.style.transform='translateX(0)';r.innerHTML=Array.from({length:28},weighted).map(card).join('')}
$('#caseGrid').onclick=e=>{const el=e.target.closest('.case');if(!el)return;selected=cases[+el.dataset.id];document.querySelectorAll('.case').forEach(x=>x.classList.toggle('selected',x===el));$('#openTitle').textContent=selected.name;$('#openBtn').disabled=false;$('#result').innerHTML=`${t().selected}: <b>${pool().length}</b> ${t().pool.toLowerCase()}`;$('#open').scrollIntoView({behavior:'smooth',block:'center'});preview();tone(360,.05)};
$('#openBtn').onclick=()=>{if(!selected||spinning)return;if(state.coins<selected.price){$('#result').className='result won';$('#result').textContent=`${t().need}: $${selected.price}`;tone(150,.15,'sawtooth');return}spinning=true;state.coins-=selected.price;updateWallet();sound('open');const btn=$('#openBtn'),win=weighted(),items=Array.from({length:34},weighted),r=$('#roulette'),winIndex=27;items[winIndex]=win;btn.disabled=true;r.style.transition='none';r.style.transform='translateX(0)';r.innerHTML=items.map(card).join('');requestAnimationFrame(()=>requestAnimationFrame(()=>{const cardWidth=188,viewportWidth=r.parentElement.clientWidth;r.style.transition='transform 5.4s cubic-bezier(.09,.73,.13,1)';r.style.transform=`translateX(${-winIndex*cardWidth+viewportWidth/2-cardWidth/2}px)`}));$('#result').className='result';$('#result').textContent=t().spinning;setTimeout(()=>{state.inventory.unshift(win);save();renderInventory();$('#result').className='result won';$('#result').innerHTML=`${t().won}: <b>${win.n}</b> $${value(win)}`;sound('win');btn.disabled=false;spinning=false},5500)};
function renderCatalog(filter='all'){const list=filter==='all'?allSkins:allSkins.filter(s=>filter==='rare'?s.rare:s.r===filter);$('#skinGrid').innerHTML=list.map(s=>card(s,'buy',allSkins.indexOf(s))).join('')}
$('#filters').onclick=e=>{if(e.target.tagName!=='BUTTON')return;document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b===e.target));renderCatalog(e.target.dataset.filter);tone(460,.04)};
$('#inventoryGrid').onclick=e=>{const btn=e.target.closest('[data-sell]');if(!btn)return;const i=+btn.dataset.sell,item=state.inventory[i];state.coins+=value(item);state.inventory.splice(i,1);save();renderInventory();sound('sell')};
$('#skinGrid').onclick=e=>{const btn=e.target.closest('[data-buy]');if(!btn)return;const item=allSkins[+btn.dataset.buy],price=value(item);if(state.coins<price){btn.textContent='НЕ ВИСТАЧАЄ $';btn.classList.add('cant-buy');setTimeout(()=>{btn.textContent=`КУПИТИ $${price}`;btn.classList.remove('cant-buy')},1100);tone(140,.12,'sawtooth');return}state.coins-=price;state.inventory.unshift(item);save();renderInventory();btn.textContent='КУПЛЕНО ✓';sound('win');setTimeout(()=>{btn.textContent=`КУПИТИ $${price}`},850)};
function upgradeSkinCard(s){return s?`<img src="${s.image}" alt="${s.n}" onerror="this.style.display='none'"><strong>${s.n}</strong><b>$${value(s)}</b>`:'<i>Обери скін</i>'}
function upgradeChance(){const from=$('#upgradeFrom'),to=$('#upgradeTo');if(!from?.value||!state.inventory.length)return 0;return Math.max(5,Math.min(85,Math.round(value(state.inventory[+from.value])/value(allSkins[+to.value])*65)))}
function renderUpgrade(){const from=$('#upgradeFrom'),to=$('#upgradeTo'),button=$('#upgradeBtn');if(!from||!to)return;const previousFrom=from.value,previousTo=to.value;from.innerHTML=state.inventory.length?state.inventory.map((s,i)=>`<option value="${i}">${s.n} — $${value(s)}</option>`).join(''):'<option value="">Немає скінів в інвентарі</option>';to.innerHTML=allSkins.map((s,i)=>`<option value="${i}">${s.n} — $${value(s)}</option>`).join('');if(state.inventory.length&&previousFrom)from.value=previousFrom;if(previousTo)to.value=previousTo;button.disabled=!state.inventory.length||upgrading;updateUpgradeChance()}
function updateUpgradeChance(){const chance=upgradeChance(),source=state.inventory[+$('#upgradeFrom').value],target=allSkins[+$('#upgradeTo').value],wheel=$('#upgradeWheel');$('#upgradePercent').textContent=chance?`${chance}%`:'—%';wheel.style.setProperty('--chance',`${chance*3.6}deg`);$('#upgradeFromCard').innerHTML=upgradeSkinCard(source);$('#upgradeToCard').innerHTML=upgradeSkinCard(target)}
$('#upgradeFrom').onchange=updateUpgradeChance;$('#upgradeTo').onchange=updateUpgradeChance;
$('#upgradeBtn').onclick=()=>{if(upgrading||!state.inventory.length)return;const from=$('#upgradeFrom'),to=$('#upgradeTo'),out=$('#upgradeResult'),index=+from.value,source=state.inventory[index],target=allSkins[+to.value],chance=upgradeChance(),needle=$('.upgrade-needle');upgrading=true;$('#upgradeBtn').disabled=true;needle.classList.remove('rolling');void needle.offsetWidth;needle.classList.add('rolling');out.textContent='КОЛЕСО КРУТИТЬСЯ…';out.className='upgrade-result';sound('open');setTimeout(()=>{state.inventory.splice(index,1);const won=Math.random()*100<chance;if(won){state.inventory.unshift(target);out.textContent=`УСПІХ! ТИ ОТРИМАВ ${target.n}.`;out.className='upgrade-result success';sound('win')}else{out.textContent=`НЕВДАЧА — ${source.n} ВТРАЧЕНО.`;out.className='upgrade-result fail';tone(130,.16,'sawtooth')}needle.classList.remove('rolling');upgrading=false;save();renderInventory()},2600)};
$('#promoBtn').onclick=()=>{$('#promoModal').hidden=false;$('#promoInput').focus();$('#promoMessage').textContent=''};$('#promoClose').onclick=()=>$('#promoModal').hidden=true;
$('#promoRedeem').onclick=()=>{const code=$('#promoInput').value.trim().toUpperCase(),msg=$('#promoMessage');if(code!=='CASELAB10000'){msg.textContent=lang==='uk'?'Невірний промокод.':lang==='ru'?'Неверный промокод.':'Invalid promo code.';msg.className='promo-message';tone(160,.15,'sawtooth');return}if(state.redeemed.includes(code)){msg.textContent=lang==='uk'?'Цей код уже використано.':lang==='ru'?'Этот код уже использован.':'This code has already been used.';msg.className='promo-message';return}state.coins+=10000;state.redeemed.push(code);save();updateWallet();msg.textContent=lang==='uk'?'Успішно: +10 000 монет!':lang==='ru'?'Успешно: +10 000 монет!':'Success: +10,000 coins!';msg.className='promo-message';sound('win')};
$('#promoInput').onkeydown=e=>{if(e.key==='Enter')$('#promoRedeem').click()};
$('#coinClicker').onclick=()=>{state.coins+=5;save();updateWallet();sound('click');const b=$('#coinClicker');b.animate([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:180})};
$('#language').onchange=e=>{lang=e.target.value;localStorage.setItem('caselab-lang',lang);applyLanguage()};
async function lookupSteam(){const raw=$('#marketSearch').value.trim();if(!raw)return;const name=/\([^)]+\)$/.test(raw)?raw:`${raw} (Field-Tested)`;const url=`https://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=${encodeURIComponent(name)}`;const out=$('#marketResult');out.textContent='Завантаження Steam Market…';try{const proxy=`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;const data=await fetch(proxy).then(r=>r.json());if(!data.success)throw Error('No market listing');out.innerHTML=`Steam Market для <b>${name}</b>: <b>${data.lowest_price||data.median_price}</b> · пропозицій: ${data.volume||'—'}`}catch{out.innerHTML=`Не вдалося отримати ціну автоматично. <a target="_blank" rel="noopener" href="https://steamcommunity.com/market/listings/730/${encodeURIComponent(name)}">Відкрити предмет у Steam Market ↗</a>`}}
$('#marketSearchBtn').onclick=lookupSteam;$('#marketSearch').onkeydown=e=>{if(e.key==='Enter')lookupSteam()};
function setPanel(name){document.body.dataset.panel=name;document.querySelectorAll('.panel-nav [data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'})}
$('.panel-nav').onclick=e=>{const button=e.target.closest('[data-panel]');if(button)setPanel(button.dataset.panel)};
$('#inventoryBtn').onclick=()=>setPanel('inventory');$('#walletBtn').onclick=()=>setPanel('cases');$('.primary').onclick=e=>{e.preventDefault();setPanel('cases');setTimeout(()=>$('#cases').scrollIntoView({behavior:'smooth'}),60)};
document.body.dataset.panel='cases';
applyLanguage();
