const cases=ALL_CASES;
const I18N={uk:{inventory:'ІНВЕНТАР',heroTitle:'Відкрий<br><em>свій</em> дроп.',heroLead:'Інтерактивний симулятор кейсів CS2. Усі предмети — віртуальні, без депозитів і реальної вартості.',chooseCase:'ОБРАТИ КЕЙС <span>↓</span>',caseStep:'01 / ВИБІР КЕЙСУ',openCase:'ВІДКРИЙ КЕЙС',caseHint:'Натисни на кейс — далі рулетка визначить твій дроп.',buyOpen:'КУПИТИ ТА ВІДКРИТИ',clickStep:'BONUS / КЛІКЕР',clickTitle:'ЗАРОБИ МОНЕТИ',clickLead:'Натискай на жетон, щоб купувати кейси. Це лише ігрова валюта.',coinsLabel:'МОНЕТ',inventoryStep:'04 / ТВОЯ КОЛЕКЦІЯ',empty:'Ще порожньо. Відкрий перший кейс.',pool:'ПРЕДМЕТІВ У ПУЛІ',selected:'У пулі',need:'Недостатньо монет',sell:'ПРОДАТИ',won:'Ти вибив',spinning:'Крутиться...'},ru:{inventory:'ИНВЕНТАРЬ',heroTitle:'Открой<br><em>свой</em> дроп.',heroLead:'Интерактивный симулятор кейсов CS2. Все предметы виртуальные, без депозитов и реальной стоимости.',chooseCase:'ВЫБРАТЬ КЕЙС <span>↓</span>',caseStep:'01 / ВЫБОР КЕЙСА',openCase:'ОТКРОЙ КЕЙС',caseHint:'Нажми на кейс — дальше рулетка определит твой дроп.',buyOpen:'КУПИТЬ И ОТКРЫТЬ',clickStep:'BONUS / КЛИКЕР',clickTitle:'ЗАРАБОТАЙ МОНЕТЫ',clickLead:'Нажимай на жетон, чтобы покупать кейсы. Это только игровая валюта.',coinsLabel:'МОНЕТ',inventoryStep:'04 / ТВОЯ КОЛЛЕКЦИЯ',empty:'Пока пусто. Открой первый кейс.',pool:'ПРЕДМЕТОВ В ПУЛЕ',selected:'В пуле',need:'Недостаточно монет',sell:'ПРОДАТЬ',won:'Ты выбил',spinning:'Крутится...'},en:{inventory:'INVENTORY',heroTitle:'Open<br><em>your</em> drop.',heroLead:'An interactive CS2 case simulator. Every item is virtual, with no deposits or real-world value.',chooseCase:'CHOOSE CASE <span>↓</span>',caseStep:'01 / CASE SELECTION',openCase:'OPEN A CASE',caseHint:'Choose a case — then the roulette decides your drop.',buyOpen:'BUY & OPEN',clickStep:'BONUS / CLICKER',clickTitle:'EARN COINS',clickLead:'Tap the token to earn coins for cases. This is game currency only.',coinsLabel:'COINS',inventoryStep:'04 / YOUR COLLECTION',empty:'Nothing here yet. Open your first case.',pool:'ITEMS IN POOL',selected:'Pool',need:'Not enough coins',sell:'SELL',won:'You unboxed',spinning:'Spinning...'}};
const UI={uk:{clicker:'КЛІКЕР',upgrade:'АПГРЕЙД',market:'РИНОК',inventory:'ІНВЕНТАР',startClicking:'ПОЧАТИ КЛІКАТИ <span>↓</span>',containersEyebrow:'ПОВНИЙ НАБІР КОНТЕЙНЕРІВ',containers:'КАПСУЛИ Й СУВЕНІРИ',containersLead:'Купуй контейнери на ринку. Щоб відкрити їх з інвентарю, потрібен ключ.',containerSearch:'Пошук кейсу, капсули або сувеніра',back:'← НАЗАД',next:'ДАЛІ →',roulette:'РУЛЕТКА',openWithKey:'ВІДКРИТИ З КЛЮЧЕМ',fullCatalog:'ПОВНИЙ КАТАЛОГ CS2',items:'ПРЕДМЕТИ Й НАКЛЕЙКИ',catalogLead:'Купуй предмети за ігрові $. Контейнери знаходяться нижче, а ключі — у цій вкладці.'},ru:{clicker:'КЛИКЕР',upgrade:'АПГРЕЙД',market:'РЫНОК',inventory:'ИНВЕНТАРЬ',startClicking:'НАЧАТЬ КЛИКАТЬ <span>↓</span>',containersEyebrow:'ПОЛНЫЙ НАБОР КОНТЕЙНЕРОВ',containers:'КАПСУЛЫ И СУВЕНИРЫ',containersLead:'Покупай контейнеры на рынке. Чтобы открыть их из инвентаря, нужен ключ.',containerSearch:'Поиск кейса, капсулы или сувенира',back:'← НАЗАД',next:'ДАЛЕЕ →',roulette:'РУЛЕТКА',openWithKey:'ОТКРЫТЬ С КЛЮЧОМ',fullCatalog:'ПОЛНЫЙ КАТАЛОГ CS2',items:'ПРЕДМЕТЫ И НАКЛЕЙКИ',catalogLead:'Покупай предметы за игровые $. Контейнеры находятся ниже, а ключи — в этой вкладке.'},en:{clicker:'CLICKER',upgrade:'UPGRADE',market:'MARKET',inventory:'INVENTORY',startClicking:'START CLICKING <span>↓</span>',containersEyebrow:'FULL CONTAINER SET',containers:'CAPSULES & SOUVENIRS',containersLead:'Buy containers on the market. You need a key to open one from inventory.',containerSearch:'Search case, capsule or souvenir',back:'← BACK',next:'NEXT →',roulette:'ROULETTE',openWithKey:'OPEN WITH KEY',fullCatalog:'FULL CS2 CATALOG',items:'ITEMS & STICKERS',catalogLead:'Buy items with game $. Containers are below, while keys are in this tab.'}};
const CATEGORY_UI={uk:{skins:'СКІНИ',stickers:'НАКЛЕЙКИ',collectibles:'КОЛЕКЦІЙНІ',graffiti:'ГРАФІТІ',agents:'АГЕНТИ',patches:'ПАТЧІ',keychains:'БРЕЛОКИ',music_kits:'МУЗИЧНІ НАБОРИ',keys:'КЛЮЧІ',tools:'ІНШЕ'},ru:{skins:'СКИНЫ',stickers:'НАКЛЕЙКИ',collectibles:'КОЛЛЕКЦИОННЫЕ',graffiti:'ГРАФФИТИ',agents:'АГЕНТЫ',patches:'НАШИВКИ',keychains:'БРЕЛОКИ',music_kits:'МУЗЫКАЛЬНЫЕ НАБОРЫ',keys:'КЛЮЧИ',tools:'ДРУГОЕ'},en:{skins:'SKINS',stickers:'STICKERS',collectibles:'COLLECTIBLES',graffiti:'GRAFFITI',agents:'AGENTS',patches:'PATCHES',keychains:'CHARMS',music_kits:'MUSIC KITS',keys:'KEYS',tools:'OTHER'}};
let lang=localStorage.getItem('caselab-lang')||'uk',selected=null,spinning=false,upgrading=false;
let state=JSON.parse(localStorage.getItem('caselab-save')||'{"coins":25,"inventory":[]}');
state.redeemed??=[];state.upgradeAssist??=false;
const allSkins=Object.values(CASE_POOLS).flat(),$=s=>document.querySelector(s),t=()=>I18N[lang];
const CATALOG_API='https://raw.githubusercontent.com/ByMykel/CSGO-API/main/public/api/en/',CATALOG_LABELS={skins:'СКІНИ',crates:'КЕЙСИ / КАПСУЛИ / СУВЕНІРИ',stickers:'НАКЛЕЙКИ',collectibles:'КОЛЕКЦІЙНІ',graffiti:'ГРАФІТІ',agents:'АГЕНТИ',patches:'ПАТЧІ',keychains:'БРЕЛОКИ',music_kits:'МУЗИЧНІ НАБОРИ',keys:'КЛЮЧІ',tools:'ІНШЕ'};let catalogCategory='skins',catalogData=[],catalogPage=0,catalogQuery='',catalogLoading=false,containerData=[],containerPage=0,containerQuery='',containerLoading=false;const catalogCache=new Map();
function save(){localStorage.setItem('caselab-save',JSON.stringify(state))}
function tone(freq,duration=.07,type='sine',volume=.04){try{const audio=new (window.AudioContext||window.webkitAudioContext)(),osc=audio.createOscillator(),gain=audio.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,audio.currentTime);gain.gain.setValueAtTime(volume,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration)}catch{}}
function sound(kind){if(kind==='click'){tone(690,.05,'square');setTimeout(()=>tone(980,.07,'sine'),40)}if(kind==='open'){tone(130,.13,'sawtooth');setTimeout(()=>tone(220,.12,'square'),120)}if(kind==='win'){tone(520,.1);setTimeout(()=>tone(780,.13),100);setTimeout(()=>tone(1040,.2),210)}if(kind==='sell'){tone(880,.05);setTimeout(()=>tone(1180,.08),60)}}
function value(s){if(Number.isFinite(s?.price))return s.price;const base=s.rare?900:({'Covert':300,'Classified':100,'Restricted':40,'Mil-Spec Grade':15}[s.r]||25);let h=0;for(const c of (s.n||s.name||''))h=(h*31+c.charCodeAt(0))>>>0;return Math.round(base+(h%Math.max(8,base)))}
function itemName(s){return s.n}
function card(s,mode='',index=-1){const action=mode==='owned'?`<button type="button" class="sell-button" data-sell="${index}" aria-label="Продати скін" title="Продати скін">+$${value(s)}</button>`:mode==='buy'?`<button type="button" class="buy-skin" data-buy="${index}">КУПИТИ $${value(s)}</button>`:'';return `<div class="skin-card" style="--rarity:${s.c}"><img class="skin-image" src="${s.image}" alt="${s.n}" loading="lazy" onerror="this.style.display='none'"><span class="type">${s.r}</span><strong>${itemName(s)}</strong>${action}<div class="rarity"></div></div>`}
function renderCases(){const grid=$('#caseGrid');grid.innerHTML=cases.map((x,i)=>`<article class="case" data-id="${i}" style="--case:${x.color}"><small>${ALL_CASE_POOLS[x.source].length} ${t().pool}</small><div class="case-box has-image"><img src="${x.image}" alt="${x.name}"></div><div class="case-name">${x.name}</div><div class="case-price">$${x.price}</div></article>`).join('');renderContainers()}
function containerValue(name){let h=0;for(const c of name)h=(h*33+c.charCodeAt(0))>>>0;return 20+h%180}
function normalizeContainer(raw){const contents=[...(raw.contains||[]),...(raw.contains_rare||[])].map(x=>({n:x.name||'Предмет CS2',r:x.rarity?.name||raw.type||'Base Grade',c:x.rarity?.color||'#b0c3d9',image:x.image||'',rare:(raw.contains_rare||[]).some(y=>y.id===x.id)}));return {n:raw.name,name:raw.name,image:raw.image,price:containerValue(raw.name),items:contents,type:raw.type||'Контейнер',kind:'container',r:raw.type||'Контейнер',c:'#d8ff38'}}
function renderContainers(){const grid=$('#containerGrid'),meta=$('#containerMeta');if(!grid)return;if(!containerData.length){if(!containerLoading)loadContainers();return}const q=containerQuery.toLowerCase(),found=q?containerData.filter(x=>x.name.toLowerCase().includes(q)):containerData,totalPages=Math.max(1,Math.ceil(found.length/24));containerPage=Math.min(containerPage,totalPages-1);const pageItems=found.slice(containerPage*24,containerPage*24+24);grid.innerHTML=pageItems.map(x=>`<article class="case external-case" data-container="${containerData.indexOf(x)}" style="--case:#d8ff38"><small>${x.items.length||'—'} ${t().pool}</small><div class="case-box has-image"><img src="${x.image}" alt="${x.name}"></div><div class="case-name">${x.name}</div><button class="buy-container" data-buy-container="${containerData.indexOf(x)}">${lang==='uk'?'КУПИТИ':lang==='ru'?'КУПИТЬ':'BUY'} $${x.price}</button></article>`).join('');meta.textContent=`${lang==='uk'?'КОНТЕЙНЕРИ':lang==='ru'?'КОНТЕЙНЕРЫ':'CONTAINERS'}: ${found.length.toLocaleString('uk-UA')}`;$('#containerPage').textContent=`${containerPage+1} / ${totalPages}`;$('#containerPrev').disabled=containerPage===0;$('#containerNext').disabled=containerPage>=totalPages-1}
async function loadContainers(){containerLoading=true;$('#containerGrid').innerHTML='<div class="empty">Завантаження кейсів, капсул і сувенірів…</div>';try{const response=await fetch(`${CATALOG_API}crates.json`);if(!response.ok)throw Error('containers');const data=await response.json();containerData=data.map(normalizeContainer).sort((a,b)=>b.items.length-a.items.length||a.name.localeCompare(b.name));renderContainers()}catch{$('#containerGrid').innerHTML='<div class="empty">Не вдалося завантажити контейнери. Спробуй оновити сторінку.</div>';$('#containerMeta').textContent='Помилка завантаження'}finally{containerLoading=false}}
function updateWallet(){ $('#coins').textContent=`$${state.coins}`;$('#clickCoins').textContent=`$${state.coins}`;$('#count').textContent=state.inventory.length }
function containerInventoryCard(s,i){const key=state.inventory.some(x=>x.kind==='key'),open=key&&s.items?.length;const text=lang==='uk'?(open?'ВІДКРИТИ':'ПОТРІБЕН КЛЮЧ'):lang==='ru'?(open?'ОТКРЫТЬ':'НУЖЕН КЛЮЧ'):(open?'OPEN':'KEY REQUIRED');return `<div class="skin-card inventory-container" style="--rarity:#d8ff38"><img class="skin-image" src="${s.image}" alt="${s.n}"><span class="type">${s.type}</span><strong>${s.n}</strong><button class="open-container" data-open-container="${i}" ${open?'':'disabled'}>${text}</button><button class="sell-button" data-sell="${i}">+$${value(s)}</button><div class="rarity"></div></div>`}
function renderInventory(){const el=$('#inventoryGrid');el.innerHTML=state.inventory.length?state.inventory.map((s,i)=>s.kind==='container'?containerInventoryCard(s,i):card(s,'owned',i)).join(''):`<div class="empty">${t().empty}</div>`;updateWallet();renderUpgrade()}
function applyLanguage(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t()[el.dataset.i18n]);document.querySelectorAll('[data-ui]').forEach(el=>el.innerHTML=UI[lang][el.dataset.ui]);document.querySelectorAll('[data-ui-placeholder]').forEach(el=>el.placeholder=UI[lang][el.dataset.uiPlaceholder]);document.querySelectorAll('#filters [data-category]').forEach(el=>el.textContent=CATEGORY_UI[lang][el.dataset.category]);$('#inventoryBtn').innerHTML=`${t().inventory} <b id="count">${state.inventory.length}</b>`;$('#language').value=lang;$('#promoTitle').textContent=lang==='uk'?'ПРОМОКОД':lang==='ru'?'ПРОМОКОД':'PROMO CODE';$('#promoHint').textContent=lang==='uk'?'Введи код, щоб отримати ігрові монети.':lang==='ru'?'Введи код, чтобы получить игровые монеты.':'Enter a code to receive game coins.';renderCases();renderCatalog();renderInventory();if(selected)$('#openTitle').textContent=selected.name}
function pool(){return selected?.items||ALL_CASE_POOLS[selected?.source]||[]}
function weighted(){const items=pool(),rare=items.filter(x=>x.rare),regular=items.filter(x=>!x.rare);if(Math.random()<.026)return rare[Math.floor(Math.random()*rare.length)];const roll=Math.random(),weights={'Covert':.0064,'Classified':.032,'Restricted':.1598,'Mil-Spec Grade':.8018};let total=0;for(const [rarity,chance] of Object.entries(weights)){total+=chance;if(roll<total){const group=regular.filter(x=>x.r===rarity);if(group.length)return group[Math.floor(Math.random()*group.length)]}}return regular[Math.floor(Math.random()*regular.length)]}
function preview(){const r=$('#roulette');r.style.transition='none';r.style.transform='translateX(0)';r.innerHTML=Array.from({length:28},weighted).map(card).join('')}
function chooseContainer(item,el){selected=item;document.querySelectorAll('.case').forEach(x=>x.classList.toggle('selected',x===el));$('#openTitle').textContent=selected.name;$('#openBtn').disabled=!pool().length;$('#result').innerHTML=pool().length?`${t().selected}: <b>${pool().length}</b> ${t().pool.toLowerCase()}`:'У цього контейнера немає доступного пулу предметів.';$('#open').scrollIntoView({behavior:'smooth',block:'center'});if(pool().length)preview();tone(360,.05)}
$('#caseGrid').onclick=e=>{const el=e.target.closest('.case');if(!el)return;chooseContainer(cases[+el.dataset.id],el)};
$('#containerGrid').onclick=e=>{const btn=e.target.closest('[data-buy-container]');if(!btn)return;const item=containerData[+btn.dataset.buyContainer],price=value(item);if(state.coins<price){btn.textContent=lang==='uk'?'НЕ ВИСТАЧАЄ $':lang==='ru'?'НЕ ХВАТАЕТ $':'NOT ENOUGH $';return}state.coins-=price;state.inventory.unshift({...item});save();renderInventory();updateWallet();btn.textContent=lang==='uk'?'КУПЛЕНО ✓':lang==='ru'?'КУПЛЕНО ✓':'BOUGHT ✓';sound('win')};$('#containerSearch').oninput=e=>{containerQuery=e.target.value.trim();containerPage=0;renderContainers()};$('#containerPrev').onclick=()=>{containerPage--;renderContainers()};$('#containerNext').onclick=()=>{containerPage++;renderContainers()};
$('#openBtn').onclick=()=>{if(!selected||spinning)return;if(state.coins<selected.price){$('#result').className='result won';$('#result').textContent=`${t().need}: $${selected.price}`;tone(150,.15,'sawtooth');return}spinning=true;state.coins-=selected.price;updateWallet();sound('open');const btn=$('#openBtn'),win=weighted(),items=Array.from({length:34},weighted),r=$('#roulette'),winIndex=27;items[winIndex]=win;btn.disabled=true;r.style.transition='none';r.style.transform='translateX(0)';r.innerHTML=items.map(card).join('');requestAnimationFrame(()=>requestAnimationFrame(()=>{const cardWidth=188,viewportWidth=r.parentElement.clientWidth;r.style.transition='transform 5.4s cubic-bezier(.09,.73,.13,1)';r.style.transform=`translateX(${-winIndex*cardWidth+viewportWidth/2-cardWidth/2}px)`}));$('#result').className='result';$('#result').textContent=t().spinning;setTimeout(()=>{state.inventory.unshift(win);save();renderInventory();$('#result').className='result won';$('#result').innerHTML=`${t().won}: <b>${win.n}</b> $${value(win)}`;sound('win');btn.disabled=false;spinning=false},5500)};
function normalizeCatalogItem(item){return {n:item.name||'Без назви',r:item.rarity?.name||item.type||CATALOG_LABELS[catalogCategory],c:item.rarity?.color||'#5d7185',image:item.image||'',rare:false,market:item.market_hash_name||item.name}}
function catalogCard(s,i){const buy=lang==='uk'?'КУПИТИ':lang==='ru'?'КУПИТЬ':'BUY';return `<div class="skin-card catalog-item" style="--rarity:${s.c}"><img class="skin-image" src="${s.image}" alt="${s.n}" loading="lazy" onerror="this.style.display='none'"><span class="type">${s.r}</span><strong>${s.n}</strong><button type="button" class="buy-skin" data-buy-catalog="${i}">${buy} $${value(s)}</button><div class="rarity"></div></div>`}
function renderCatalog(){const grid=$('#skinGrid'),meta=$('#catalogMeta');if(!catalogData.length){if(!catalogLoading)loadCatalog(catalogCategory);return}const q=catalogQuery.toLowerCase(),found=q?catalogData.filter(s=>s.n.toLowerCase().includes(q)):catalogData,totalPages=Math.max(1,Math.ceil(found.length/48));catalogPage=Math.min(catalogPage,totalPages-1);const start=catalogPage*48,visible=found.slice(start,start+48);grid.innerHTML=visible.map(s=>catalogCard(s,catalogData.indexOf(s))).join('');meta.textContent=`${CATALOG_LABELS[catalogCategory]}: ${found.length.toLocaleString('uk-UA')} предметів`;$('#catalogPage').textContent=`${catalogPage+1} / ${totalPages}`;$('#catalogPrev').disabled=catalogPage===0;$('#catalogNext').disabled=catalogPage>=totalPages-1}
async function loadCatalog(category){catalogCategory=category;catalogPage=0;catalogQuery='';$('#catalogSearch').value='';if(catalogCache.has(category)){catalogData=catalogCache.get(category);renderCatalog();return}catalogLoading=true;$('#skinGrid').innerHTML='<div class="empty">Завантаження повного каталогу CS2…</div>';$('#catalogMeta').textContent='Завантаження…';try{const response=await fetch(`${CATALOG_API}${category}.json`);if(!response.ok)throw Error('catalog');const data=await response.json();catalogData=data.map(normalizeCatalogItem);catalogCache.set(category,catalogData);renderCatalog()}catch{catalogData=[];$('#skinGrid').innerHTML='<div class="empty">Не вдалося завантажити каталог. Спробуй ще раз.</div>';$('#catalogMeta').textContent='Помилка завантаження'}finally{catalogLoading=false}}
$('#filters').onclick=e=>{const button=e.target.closest('[data-category]');if(!button)return;document.querySelectorAll('#filters button').forEach(b=>b.classList.toggle('active',b===button));tone(460,.04);loadCatalog(button.dataset.category)};
$('#catalogSearch').oninput=e=>{catalogQuery=e.target.value.trim();catalogPage=0;renderCatalog()};$('#catalogPrev').onclick=()=>{catalogPage--;renderCatalog()};$('#catalogNext').onclick=()=>{catalogPage++;renderCatalog()};
$('#inventoryGrid').onclick=e=>{const open=e.target.closest('[data-open-container]');if(open){const i=+open.dataset.openContainer,keyIndex=state.inventory.findIndex(x=>x.kind==='key'),item=state.inventory[i];if(keyIndex<0||!item?.items?.length)return;state.inventory.splice(i,1);state.inventory.splice(state.inventory.findIndex(x=>x.kind==='key'),1);selected={...item,price:0};save();renderInventory();setPanel('market');setTimeout(()=>{$('#open').scrollIntoView({behavior:'smooth',block:'center'});preview();$('#openBtn').click()},100);return}const btn=e.target.closest('[data-sell]');if(!btn)return;const i=+btn.dataset.sell,item=state.inventory[i];state.coins+=value(item);state.inventory.splice(i,1);save();renderInventory();sound('sell')};
$('#skinGrid').onclick=e=>{const btn=e.target.closest('[data-buy],[data-buy-catalog]');if(!btn)return;const raw=btn.dataset.buyCatalog!==undefined?catalogData[+btn.dataset.buyCatalog]:allSkins[+btn.dataset.buy],item=catalogCategory==='keys'?{...raw,kind:'key'}:raw,price=value(item);if(!item)return;if(state.coins<price){btn.textContent=lang==='uk'?'НЕ ВИСТАЧАЄ $':lang==='ru'?'НЕ ХВАТАЕТ $':'NOT ENOUGH $';btn.classList.add('cant-buy');setTimeout(()=>{btn.textContent=`${lang==='uk'?'КУПИТИ':lang==='ru'?'КУПИТЬ':'BUY'} $${price}`;btn.classList.remove('cant-buy')},1100);tone(140,.12,'sawtooth');return}state.coins-=price;state.inventory.unshift(item);save();renderInventory();btn.textContent=lang==='en'?'BOUGHT ✓':'КУПЛЕНО ✓';sound('win');setTimeout(()=>{btn.textContent=`${lang==='uk'?'КУПИТИ':lang==='ru'?'КУПИТЬ':'BUY'} $${price}`},850)};
function upgradeSkinCard(s){return s?`<img src="${s.image}" alt="${s.n}" onerror="this.style.display='none'"><strong>${s.n}</strong><b>$${value(s)}</b>`:'<i>Обери скін</i>'}
function upgradeChance(){const from=$('#upgradeFrom'),to=$('#upgradeTo');if(!from||from.value===''||!state.inventory.length)return 0;const source=state.inventory[+from.value],target=allSkins[+to.value];if(!source||!target||value(target)<=value(source))return 0;return Math.max(5,Math.min(85,Math.round(value(source)/value(target)*65)))}
function upgradeZone(chance){const arc=chance*3.6;return {start:180-arc/2,end:180+arc/2}}
function inUpgradeZone(deg,zone){return deg>=zone.start&&deg<=zone.end}
function randomOutsideZone(zone){let deg;do{deg=Math.random()*360}while(inUpgradeZone(deg,zone));return deg}
function renderUpgrade(){const from=$('#upgradeFrom'),to=$('#upgradeTo'),button=$('#upgradeBtn');if(!from||!to)return;const previousFrom=from.value,previousTo=to.value,usable=state.inventory.map((s,i)=>({s,i})).filter(x=>!x.s.kind);from.innerHTML=usable.length?usable.map(({s,i})=>`<option value="${i}">${s.n} — $${value(s)}</option>`).join(''):`<option value="">${lang==='uk'?'Немає скінів в інвентарі':lang==='ru'?'Нет скинов в инвентаре':'No skins in inventory'}</option>`;to.innerHTML=allSkins.map((s,i)=>`<option value="${i}">${s.n} — $${value(s)}</option>`).join('');if(usable.length&&previousFrom!==''&&state.inventory[+previousFrom]&&!state.inventory[+previousFrom].kind)from.value=previousFrom;if(previousTo)to.value=previousTo;updateUpgradeChance();button.disabled=!upgradeChance()||upgrading}
function updateUpgradeChance(){const chance=upgradeChance(),source=state.inventory[+$('#upgradeFrom').value],target=allSkins[+$('#upgradeTo').value],wheel=$('#upgradeWheel'),button=$('#upgradeBtn'),zone=upgradeZone(chance);$('#upgradePercent').textContent=chance?`${chance}%`:'—%';wheel.style.setProperty('--zone-start',`${zone.start}deg`);wheel.style.setProperty('--zone-end',`${zone.end}deg`);$('#upgradeFromCard').innerHTML=upgradeSkinCard(source);$('#upgradeToCard').innerHTML=upgradeSkinCard(target);button.disabled=!chance||upgrading;if(state.inventory.length&&!chance)$('#upgradeResult').textContent='ОБЕРИ СКІН, ЯКИЙ ДОРОЖЧИЙ ЗА ТВІЙ.'}
$('#upgradeFrom').onchange=updateUpgradeChance;$('#upgradeTo').onchange=updateUpgradeChance;
$('#upgradeBtn').onclick=()=>{if(upgrading||!state.inventory.length)return;const from=$('#upgradeFrom'),to=$('#upgradeTo'),out=$('#upgradeResult'),index=+from.value,source=state.inventory[index],target=allSkins[+to.value],chance=upgradeChance(),zone=upgradeZone(chance),needle=$('.upgrade-needle');if(!chance)return;const plannedWin=state.upgradeAssist||Math.random()*100<chance,stop=plannedWin?zone.start+Math.random()*(zone.end-zone.start):randomOutsideZone(zone),spinEnd=13*360+stop;upgrading=true;$('#upgradeBtn').disabled=true;needle.style.setProperty('--spin-end',`${spinEnd}deg`);needle.style.setProperty('--spin-rush',`${spinEnd-720}deg`);needle.classList.remove('rolling');void needle.offsetWidth;needle.classList.add('rolling');out.textContent='СТРІЛКА КРУТИТЬСЯ…';out.className='upgrade-result';sound('open');setTimeout(()=>{const won=inUpgradeZone(stop,zone);state.inventory.splice(index,1);if(won){state.inventory.unshift(target);out.textContent=`УСПІХ! СТРІЛКА В ЗЕЛЕНІЙ ЗОНІ — ТИ ОТРИМАВ ${target.n}.`;out.className='upgrade-result success';sound('win')}else{out.textContent=`НЕВДАЧА — СТРІЛКА НЕ ПОТРАПИЛА В ЗЕЛЕНУ ЗОНУ. ${source.n} ВТРАЧЕНО.`;out.className='upgrade-result fail';tone(130,.16,'sawtooth')}needle.classList.remove('rolling');upgrading=false;save();renderInventory()},5200)};
$('#promoBtn').onclick=()=>{$('#promoModal').hidden=false;$('#promoInput').focus();$('#promoMessage').textContent=''};$('#promoClose').onclick=()=>$('#promoModal').hidden=true;
$('#promoRedeem').onclick=()=>{const code=$('#promoInput').value.trim().toUpperCase(),msg=$('#promoMessage');if(!['CASELAB10000','ALLINWIN'].includes(code)){msg.textContent=lang==='uk'?'Невірний промокод.':lang==='ru'?'Неверный промокод.':'Invalid promo code.';msg.className='promo-message';tone(160,.15,'sawtooth');return}if(state.redeemed.includes(code)){msg.textContent=lang==='uk'?'Цей код уже використано.':lang==='ru'?'Этот код уже использован.':'This code has already been used.';msg.className='promo-message';return}state.redeemed.push(code);if(code==='CASELAB10000'){state.coins+=10000;msg.textContent=lang==='uk'?'Успішно: +10 000 монет!':lang==='ru'?'Успешно: +10 000 монет!':'Success: +10,000 coins!'}else{state.upgradeAssist=true;msg.textContent=lang==='uk'?'Режим удачі активний: апгрейди потраплятимуть у зелену зону. Відсоток шансу не змінюється.':lang==='ru'?'Режим удачи активен: апгрейды будут попадать в зеленую зону. Процент шанса не меняется.':'Luck mode active: upgrades land in the green zone. Displayed chance stays the same.'}save();updateWallet();msg.className='promo-message';sound('win')};
$('#promoInput').onkeydown=e=>{if(e.key==='Enter')$('#promoRedeem').click()};
$('#coinClicker').onclick=()=>{state.coins+=5;save();updateWallet();sound('click');const b=$('#coinClicker');b.animate([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],{duration:180})};
$('#language').onchange=e=>{lang=e.target.value;localStorage.setItem('caselab-lang',lang);applyLanguage()};
async function lookupSteam(){const raw=$('#marketSearch').value.trim();if(!raw)return;const name=/\([^)]+\)$/.test(raw)?raw:`${raw} (Factory New)`;const url=`https://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=${encodeURIComponent(name)}`;const out=$('#marketResult');out.textContent='Завантаження Steam Market…';try{const proxy=`https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`;const data=await fetch(proxy).then(r=>r.json());if(!data.success)throw Error('No market listing');out.innerHTML=`Steam Market для <b>${name}</b>: <b>${data.lowest_price||data.median_price}</b> · пропозицій: ${data.volume||'—'}`}catch{out.innerHTML=`Не вдалося отримати ціну автоматично. <a target="_blank" rel="noopener" href="https://steamcommunity.com/market/listings/730/${encodeURIComponent(name)}">Відкрити предмет у Steam Market ↗</a>`}}
$('#marketSearchBtn').onclick=lookupSteam;$('#marketSearch').onkeydown=e=>{if(e.key==='Enter')lookupSteam()};
function setPanel(name){document.body.dataset.panel=name;document.querySelectorAll('.panel-nav [data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'})}
$('.panel-nav').onclick=e=>{const button=e.target.closest('[data-panel]');if(button)setPanel(button.dataset.panel)};
$('#inventoryBtn').onclick=()=>setPanel('inventory');$('#walletBtn').onclick=()=>setPanel('cases');$('.primary').onclick=e=>{e.preventDefault();setPanel('cases');setTimeout(()=>$('#clicker').scrollIntoView({behavior:'smooth'}),60)};
document.body.dataset.panel='cases';
applyLanguage();
